### ISSUE TITLE
Domains > App Count Not Updated

### ISSUE THREAD

**Issue by jeremy-west** [PlaceOS/backoffice#101]
**Describe the bug**
Under Domains > Applications, the count does not represent the number of applications contained in the list.

**Expected behavior**
A count of total applications should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/44023728/91693074-d42fe680-ebad-11ea-99e6-77edb96be620.png)

**Comment by MrYuion** [comment]
Found the issue. The header with the count is capitalized on that server whereas it's lowercase on the partner env.

**Comment by kimburgess** [comment]
This behaviour is still occurring. This is visible in the current alpha build:
![2FDA6596-C2C9-471D-96B5-61EF7A4137BE](https://user-images.githubusercontent.com/843652/113106173-c9bdf400-9245-11eb-8f11-a53d2dcaad1e.jpeg)

**Comment by MrYuion** [comment]
@kimburgess, should be fine now.
