### ISSUE TITLE
Users > No History

### ISSUE THREAD

**Issue by jeremy-west** [PlaceOS/backoffice#103]
**Describe the bug**
User login history is not shown.

**To Reproduce**
1. Go to users
2. Select user and open history
3. No history available

**Expected behavior**
Should show user login history.

**Screenshots**
![image](https://user-images.githubusercontent.com/44023728/91918447-3c91db80-ed06-11ea-9e77-2a89b88b825d.png)

**Comment by MrYuion** [comment]
There is no API for this at the moment I believe.

**Comment by caspiano** [comment]
This is being replaced by the embedded kibana. We'll have a dashboard configured to filter logs by `user_id`

**Comment by jeremyw24** [comment]
@MrYuion @caspiano can we close this issue if functionality will be delivered elsewhere?

**Comment by caspiano** [comment]
Agreed, though the content should be preserved in the issue that's requesting this feature in the embedded kibana form.

thoughts @stakach
