### ISSUE TITLE
Setting editor de-focuses under iOS

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#105]
**Describe the bug**
When attempting to interact with the settings editor under iOS the control de-focuses immediately following selection.

Edit: this looks to only happen when using an external keyboard. If this is disabled and the internal popup soft keyboard is used, behaviour is as expected.

**To Reproduce**
1. Go to any editor input (on a driver, zone, domain etc)
2. Tap the main settings editor control to select

**Expected behavior**
Focus should remain on editor to allow for keyboard input / editing.

**Smartphone (please complete the following information):**
 - Device: iPad Pro
 - OS: iOS13
 - Browser: Safari

**Comment by MrYuion** [comment]
I've made some changes but I'm not sure if I've fixed it. I can't reproduce it in the iOS simulator but that's not a guarantee.

**Comment by KimBurgess** [comment]
No probs. It there's a build somewhere I can give it a quick test here.

**Comment by MrYuion** [comment]
Do you have the dev/partner env setup? With everything up to date it you should be able to test it from there.

**Comment by KimBurgess** [comment]
Testing with the CI build from 7dd89ea shows the same behaviour.

**Comment by MrYuion** [comment]
I think it might be an issues with the editor. How does it run for on their playground?
https://microsoft.github.io/monaco-editor/playground.html

**Comment by KimBurgess** [comment]
All solid there.

**Comment by jeremyw24** [comment]
@MrYuion any update on this issue please?

**Comment by MrYuion** [comment]
No progress.

**Comment by kimburgess** [comment]
Confirming this behaviour is still occurring as of today (build 20f9aeb) and iOS 14.4.1.

**Comment by kimburgess** [comment]
Just stumbled across some new interesting behaviour: it _does_ work if you zoom slightly.
![](https://user-images.githubusercontent.com/843652/111986924-440dba80-8b5a-11eb-9d51-da1aa1e6c383.mov)

Summary of current state:
- Monaco editor **does** work (under all conditions) on [their playground](https://microsoft.github.io/monaco-editor/playground.html). Worth noting that that is running 0.23.0, where things here are pinned to 0.22.0.
- The instance in Backoffice **does** work if interactive with via a standalone iOS device.
- Instance is backoffice **does not** work when an external keyboard (either Bluetooth or USB) is attached.
- Zooming the view slightly provides a workaround.

Given when no keyboard is attached the view is bumped / resized to make way for the on screen keyboard and this likely triggers some similar events to when the view changes via a pinch/zoom interaction, hope this is of use!

**Comment by MrYuion** [comment]
Fixed. Changing `user-select` CSS property causes issues with input fields on iOS.
