### ISSUE TITLE
Not populating default URI

### ISSUE THREAD

**Issue by pkheav** [PlaceOS/backoffice#106]
**Expected behavior**
Should populate field `default_uri` in IP Address or FQDN box

**Screenshots**
![image](https://user-images.githubusercontent.com/18463731/93602203-3cf2cd80-f9ba-11ea-965f-657bdb15eb12.png)

**Desktop (please complete the following information):**
 - MacOS
 - Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by MrYuion** [comment]
I think your driver's type is incorrect. URI is only available for service and websocket drivers. A URI is not a IP address or FQDN.
