### ISSUE TITLE
Weird add new behaviour

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#11]
Looks like add new list is being filtered by the front-end?
On one system I have the option to add two modules, on the other only one.
Makes the same request to the backend which returns both results.. But front-end is only showing one result and only in this system.. Refreshing the page made no difference either.

![image](https://user-images.githubusercontent.com/368013/77213379-bcfcbf80-6b5e-11ea-810b-2e6e3e7ff674.png)

Then the other system
![image](https://user-images.githubusercontent.com/368013/77213463-04834b80-6b5f-11ea-9e93-f99cc06a952d.png)

**Comment by stakach** [comment]
Haven't been able to replicate this, super weird

**Comment by MrYuion** [comment]
It will filter out modules that are already in the system
