### ISSUE TITLE
Repos > Edit any Repo with Type: Driver Repository > No option to change branch

### ISSUE THREAD

**Issue by pkheav** [PlaceOS/backoffice#111]
[BACKOFFICE][APP] 1c31858 | Built: Today at 12:19AM

![image](https://user-images.githubusercontent.com/18463731/96112098-04bbad80-0eda-11eb-8b89-37a666227665.png)

**Comment by MrYuion** [comment]
The backend currently doesn't support that as individual drivers can run on different commits of the repo.
