### ISSUE TITLE
Not entering a value for a param when executing a command doesn't use the default value

### ISSUE THREAD

**Issue by pkheav** [PlaceOS/backoffice#112]
[BACKOFFICE][APP] 1c31858 | Built: Today at 12:19AM

Request method: POST
Request url: https://ashrae-dev.aca.im/api/engine/v2/systems/sys-FhxwfjjvA2N/Calendar_1/create_event
Payload: `["Test",1602710522,1602710584,null,null,null,null,"Room-215@ashrae.org"]`
![image](https://user-images.githubusercontent.com/18463731/96114053-00dd5a80-0edd-11eb-8673-25dfcfba04be.png)

which the backend responds with a 500 error and
`{"error":"request failed","sys_id":"sys-FhxwfjjvA2N","module_name":"Calendar","index":1,"message":"module raised: Expected String but was Null at 1:1 (JSON::ParseException)","backtrace":["../usr/share/crystal/src/json/pull_parser.cr:528:5 in 'parse_exception'","../usr/share/crystal/src/json/pull_parser.cr:520:5 in 'expect_kind'","../usr/share/crystal/src/json/pull_parser.cr:199:5 in 'read_string'","../usr/share/crystal/src/json/from_json.cr:132:3 in 'new'","../usr/share/crystal/src/json/from_json.cr:13:3 in 'from_json'","repositories/drivers/drivers/place/calendar.cr:5:1 in '->'","../usr/share/crystal/src/primitives.cr:255:3 in 'execute'","repositories/drivers/lib/placeos-driver/src/placeos-driver/driver_manager.cr:128:5 in 'execute'","repositories/drivers/lib/placeos-driver/src/placeos-driver/driver_manager.cr:150:18 in 'process'","repositories/drivers/lib/placeos-driver/src/placeos-driver/driver_manager.cr:138:9 in '->'","../usr/share/crystal/src/primitives.cr:255:3 in 'run'","../usr/share/crystal/src/fiber.cr:92:34 in '->'","???"]}`

This is the method I'm trying to execute so it's failing because I didn't pass anything for description so doesn't use the default value of an empty string. https://github.com/PlaceOS/drivers/blob/d830769c303516255ca8cdf8ba0967e240892072/drivers/place/calendar.cr#L135-L144

Could be a core issue as I'm not sure what else the frontend is supposed to pass except for null when nothing is entered for a param.

**Comment by MrYuion** [comment]
@stakach, I'm not too sure how I should handle this. I don't think the frontend knows what the default values are. Should I be passing undefined or something? I don't think undefined exists in JSON though.
