### ISSUE TITLE
Numbers Same Size as Upper Case Letters

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/backoffice#114]
**Describe the bug**
Numbers are the same size as the lowercase letters which looks odd when numbers are directly followed by upper case letters.

**To Reproduce**
Create a system with a  number+letter i.e. 18.01M

**Expected behavior**
Numbers should be same size as upper case.

**Screenshots**
![image](https://user-images.githubusercontent.com/4019090/97530827-0a9bad80-1a07-11eb-8304-881f60ba0e63.png)

**Comment by MrYuion** [comment]
That's an issue with the font not the application. There isn't much I can do about that.

**Comment by jeremyw24** [comment]
@MrYuion can we change the font?

**Comment by MrYuion** [comment]
Yeah, I've already changed it.
