### ISSUE TITLE
new feature OR Extension: CRUD of STAFF API Tenants

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#116]
In reference to the PlaceOS Staff API
https://github.com/place-labs/staff-api

A prerequisite for the API becoming functional is the addition of Tenants with an authenticated HTTPS POST.
Please either:
    - create either a backoffice extension (for DOMAINS) 
    - OR extend backoffice ADMIN tab, new STAFF API page
to have staff api tenant functionality:

https://placeoscalendar.docs.apiary.io/#reference/0/tenants/
1. List Tenants for each Domain
2. Add tenant for an existing Domain
3. Delete existing tenant from an existing Domain

**Comment by w-le** [comment]
my preferece is to build it directly into backoffice, instead of as an extension (like the map area editor)
as the staff api is SO common, and it will remove that one extra unintuitive step to add the extension to backoffice

**Comment by MrYuion** [comment]
That should be good to go now.

**Comment by w-le** [comment]
one small fix required is that the POST Body is missing the user selected PlaceOS `domain:` for both platform types (not to be confused with `credentials.domain` for Google platform`

Note that the posted domain must ONLY include the domain and NOT the port or path
e.g. `localhost` not `localhost:8443/backoffice`

**Comment by w-le** [comment]
one small fix required is that the POST Body is missing the user selected PlaceOS `domain:` for both platform types (not to be confused with `credentials.domain` for Google platform`

Note that the posted domain must ONLY include the domain and NOT the port or path
e.g. `localhost` not `localhost:8443/backoffice`

**Comment by MrYuion** [comment]
Hmm... I'm not sure If I should change that. It currently used the `domain` value set in the selected domain. Shouldn't that value represent the correct value if that how you wish it to be used?

**Comment by w-le** [comment]
I expected so, but when testing in partner-environment, the text listed in the domain selector drop down at the top left of this new admin/staff-api has `:8443/backoffice` in it, which it shouldn't

**Comment by MrYuion** [comment]
Currently the domain field on domains are free text. Should I restrict it to be a FQDN or IP address?

**Comment by w-le** [comment]
Thoughts @stakach ? Any negative impact there?

**Comment by w-le** [comment]
I'm gonna go ahead and decide: yes, as I don't see any drawback.
So on the backoffice Domain Add/Edit modal, perform some validation on the Domain field such that it must be a valid domain
example valid domains are:
- localhost
- placeos.local
- www.example.com
- place.tech
- 10.0.0.1

invalid ones are:
- https://localhost  (no protocol allowed)
- localhost:8443  (no ports allowed)

**Comment by KimBurgess** [comment]
Looks like there's still some fields missing here. Testing with the current alpha build and seeing a 500 due to `Missing hash key: "domain"`.

**Comment by MrYuion** [comment]
Should be fixed now.
