### ISSUE TITLE
Module state not reporting correctly

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#119]
**Describe the bug**
When there is more than one of the same type of module in a system, the state icon reflects the state of the first module only. 
For example
If Camera_1 changes state to offline and shows a red icon, Camera_2 also shows a red icon (looking at Camera_2 state shows "connected": true)
If Camera_1 is online, showing green and Camera_2 goes offline, Camera_2 icon continues to show green (state shows "connected": false)

**Expected behavior**
State icons should reflect the state of the module.

**Additional context**
Backoffice commit b746e20
API v1.17.10

**Comment by MrYuion** [comment]
This should be fixed now.
