### ISSUE TITLE
Issue on page Repositories

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#121]
**Describe the bug**
Backoffice allows spaces to be entered as a driver repository folder

**To Reproduce**
{"updated_at":0,"version":0,"branch":"master","repo_type":"Driver","id":"","commit_hash":"HEAD","name":"randomness","folder_name":"dont allow spaces in folder names","description":"","uri":"https://github.com/placeos/drivers","username":"","password":""}

**Expected behavior**
Backoffice should complain about spaces or add underscores

**Hash:** 5c15b02
**Built:** 12 Nov 2020, 2:56 PM

Note: api should also not allow this

Breaks `core` 
level=WARN time=2020-11-12T08:30:26Z source=place_os.resource type=PlaceOS::Model::Repository handler=PlaceOS::Core::Cloning action=Created id=repo-G5zcEqYaqI9 error=randomness: failed to install shards

**Comment by MrYuion** [comment]
@stakach or @caspiano, I've made a fix on the frontend. Are you able to look at this on the backend?
