### ISSUE TITLE
chore(kb shortcuts): D (delete) > change to del button or remove

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#126]
(not urgent)
"D" deletes the current item, but I use Alt+D ALOT to set focus to the address bar for navigation.
Some people may also use ctrl+D to bookmark the page.

I don't think that "D" is an obvious or standard shortcut for deletion in a web page. Is it possible to either:
- change the key binding for delete to the DELETE key
OR
- remove the D binding, it doesn't save a lot of time anyway (just replaces 2 clicks with 1 kb stroke) as you can't keep pressing it to delete several items.

**Comment by MrYuion** [comment]
Easy done.

**Comment by w-le** [comment]
and there was much rejoicing
