### ISSUE TITLE
Editing a module on systems page results in a 404 call

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#128]
**Describe the bug**
Pressing save on a module after editing it results in a empty systems view and a 404 result.

**To Reproduce**
1. View System
2. Select modules tab
3. Update a module and press save

Results in an error message and a 404 error can be seen in browser logs

**Expected behavior**
View should show System modules

**Additional context**
Backoffice commit hash d407325

**Comment by MrYuion** [comment]
Fixed in commit 43c5f43
