### ISSUE TITLE
Clicking on a repository reverts to default systems view

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#130]
**Describe the bug**
Clicking on a repo to view or edit load the default systems view

**To Reproduce**
1. Click on left menu item "Repos"
2. Click on a repo

Result: Shows default systems view

**Expected behavior**
Show info about the selected repository

**Additional context**
Backoffice Version Hash e547270

**Comment by MrYuion** [comment]
Fixed by commit c8a0c3d
