### ISSUE TITLE
Add Existing driver, please show driver name

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#133]
**Is your feature request related to a problem? Please describe.**
When I go to add an existing driver the list only shows the Class name and not the module name making it very hard to choose the correct module.

**Describe the solution you'd like**
I think it would be better to show the module Name then display the module class on a different line or some other way (in brackets, after a dash etc)

**Note**
This is in the Add Existing module dialog in System view

**Comment by MrYuion** [comment]
Hmm... the module name is the class though...

**Comment by PhilPearson** [comment]
Right, sorry, I mean the driver name.
If I add 7 Amplifiers 3 being Extron, 4 being Crown, the dropdown list only shows me `Amplifier`.
I don't know which one is Extron vs Crown.
Probably fine to leave as is as personally I would rarely use Add Existing. Its only an issue at the moment as I'm forced to use it due to https://github.com/PlaceOS/backoffice/issues/132

**Comment by MrYuion** [comment]
@stakach / @caspiano, is it possible to add the driver name to the returned module data? I'd rather not have to make a second request for every module to get this data.
