### ISSUE TITLE
Add existing does not show logic modules

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#134]
**Describe the bug**
Due to the issue noted here https://github.com/PlaceOS/backoffice/issues/132 I then tried to add the existing module to the system but the search does not return results on logic modules.

**To Reproduce**
1. In System view add a new logic module (due to 132 the driver is not assigned to the system)
2. Search for the module
3. no results found, unable to add to the system

**Expected behavior**
Be able to add logic modules that have not already been assigned to a system.

**Additional context**
Backoffice commit hash 7ec06e8

**Note**
Could potentially be resolved with 132

**Comment by MrYuion** [comment]
I believe the cause of this is the same as #132
