### ISSUE TITLE
Module order is not based on the order in which you add modules

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#136]
**Describe the bug**
I added two modules, both use the same driver (but have different names), the first one added as class_1, the 2nd as class_2 as expected. Due to https://github.com/PlaceOS/backoffice/issues/135 I was not able to swap them so I removed class_1 (class_2 now became class_1 as expected) but when re-creating the same module, class_1 was bumped to class_2.

**Comment by MrYuion** [comment]
The cause is the same as #135
