### ISSUE TITLE
Driver compiled status always false

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/backoffice#140]
**Describe the bug**
Testing with alpha build https://github.com/PlaceOS/backoffice/commit/bf05185521aa8f484ab570c7606415a3103bb9fa, the compiled status of drivers always shows false.

**To Reproduce**
1. Go to 'Drivers'
2. Click on _any driver_

**Expected behavior**
Compiled status should reflect driver compilation status.

**Additional context**
Core logs appear to indicate that compilation is successful.

**Comment by MrYuion** [comment]
Yeah, it's not making the request to check.

**Comment by KimBurgess** [comment]
That's got to be a record for the time to fix. Confirming working here - cheers!
