### ISSUE TITLE
Saving array as metadata fails with JSON validation error

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/backoffice#143]
**Describe the bug**
When attempting to save an array against a metadata key this errors with a JSON validation error (when the entered value is valid JSON). Unfortunately I can't replicate locally (due to #105), but was able to observe during a call with an external team.

**To Reproduce**
1. Go to Zones
2. Select a zone
3. Add a new metadata key
4. Attempt to save an array based value against the key.

**Expected behaviour**
The value should save if it is valid JSON.

**Additional context**
Tagging @w-le as a co-viewer and someone who may be able to add more context.

**Comment by MrYuion** [comment]
Hmm... adding arrays seem to be working for me.
<img width="940" alt="Screen Shot 2020-12-07 at 7 46 57 pm" src="https://user-images.githubusercontent.com/20103948/101329088-0778c480-38c5-11eb-86f7-7609660b32ac.png">

**Comment by KimBurgess** [comment]
Yep - definite non-issue. This was being caused by a chat client inserting some odd non-printable chars.
