### ISSUE TITLE
Tooltip in settings is blocking ability to select text

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#150]
**Describe the bug**
When trying to select text in Merged settings, the `Local setting from Unencrypted` tool tip gets in the way.

**To Reproduce**
1. Go to any module
2. Attempt to copy/paste top level entries in Merged settings

**Expected behavior**
Tooltip should not be in the way of the cursor.

**Screenshots**
![2c754aa1-4ee3-4ab7-ae2d-10c553ae3529](https://user-images.githubusercontent.com/14122378/102150630-04289e80-3eac-11eb-930b-765baa356c18.PNG)

**Additional context**
Backoffice commit hash 131fc93

**Comment by MrYuion** [comment]
The tooltips are handled by the editor. There isn't much I can do about them. They should only be showing when you hover over underlined words. I've made them non-interactive so you should be able to select through them.
