### ISSUE TITLE
Debug console does not use all of the available width

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#151]
**Describe the bug**
The debug console text area is a fixed width yet the window itself can be made wider.

**Expected behavior**
text area should match the window area.

**Screenshots**
![79fbc747-b7f7-418b-87e2-878473f80445](https://user-images.githubusercontent.com/14122378/102151042-e14aba00-3eac-11eb-9429-6ba5f24d10bb.PNG)

**Additional context**
Backoffice commit hash 131fc93

**Comment by MrYuion** [comment]
Hmm... seems to be working fine for me.
<img width="1563" alt="Screen Shot 2020-12-15 at 3 31 41 pm" src="https://user-images.githubusercontent.com/20103948/102171492-c008be80-3eea-11eb-9a9b-e4f2fe102888.png">

**Comment by PhilPearson** [comment]
I've just rolled back a newer version to 131fc93 and confirmed that it exists there but has been fixed since.
Not sure which version fixes it but latest is fine.
