### ISSUE TITLE
Filtering for modules returns all modules

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#152]
**Describe the bug**
Regardless of what gets entered into the Filter Modules search box, all modules get returned

**To Reproduce**
1. Go to Modules
2. Enter a search term
3. Filter is not applied and all modules are shown

**Expected behavior**
Filter should get applied, showing only modules that match

**Additional context**
Backoffice commit hash 131fc93
Rest api 1.17.10

Also tried rest-api v 1.17.11 and backoffice commit hash 752bb14

**Comment by MrYuion** [comment]
This is a backend issue. Raise it in `rest-api`
