### ISSUE TITLE
Support user encounters many views with constant loading spinner icon

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#154]
**Describe the bug**
A user with Support level privileges is stuck watching endless loading spinner

**To Reproduce**
1. log into Backoffice as a user with `Support` level privileges
2. View any of the following:
 * Systems | Zones
 * Modules | Settings
 * Drivers | Compiled status
 * Users

**Expected behavior**
Support user should be able to view items that they have access to or be prevented from being able to access these items.

**Additional context**
Backoffice Commit Hash: ae88a8a

**Comment by jeremyw24** [comment]
@MrYuion I was able to confirm this behaviour still exists on the latest backoffice build 523e9cf.

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/a4dbc238-2491-4999-877b-3942c9752948)

![image.png](https://images.zenhubusercontent.com/5f7efb49f50062d6404b6473/590ab596-7844-4f3c-a0c6-ace821e64a7a)

**Comment by MrYuion** [comment]
@caspiano, some of the settings should be returned for support users.
