### ISSUE TITLE
When adding a driver some details are not filled in

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#16]
The details request returns defaults such as port which are not being used currently.
The various fields that can be returned are: `details response` => `driver add form field`

```
name => Name
generic_name => Module name
description => Description
tcp_port => Default Port number
udp_port => Default Port number
uri_base => Default URI
default_settings => to be added to unencrypted settings as a second API call after object creation
```

If possible the default settings should be placed into the unencrypted settings object (this will require a second API call however it is definitely useful and required to make things seamless)

<img width="367" alt="image" src="https://user-images.githubusercontent.com/368013/77874014-5af73500-7297-11ea-9949-4df6a19b3da0.png">

In terms of the driver `role`

* If `tcp_port` or `udp_port` are present then default it to `Device`
* if `uri_base` is present then default it to `Service`
* otherwise default it to `Logic` as it does currently

**Comment by MrYuion** [comment]
Is there any priority preference of which of the port fields are used? 
Or will only one of them be set at any time?

**Comment by stakach** [comment]
Only one will be set at any time.

**Comment by stakach** [comment]
Sweet, looking good!
