### ISSUE TITLE
systems>zones>search: filter results do not show first hit

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#160]
issues present in 3f3f91363cdffec216df786f275cb8ab27c5702f
response has 2 hits, drop down does not show first hit
![image](https://user-images.githubusercontent.com/10395560/107729341-970a7b80-6d2b-11eb-9fd7-cc4aad55666c.png)

**Comment by MrYuion** [comment]
Yeah, it hides options that have already been added to the system.
