### ISSUE TITLE
User and Repo modals cannot be used under iOS

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#161]
**Describe the bug**
When modals on either the 'Repositories' or 'Users' views display, it is not possible to continue interaction any touch based interaction. This impacts both adding or editing entities of these types. Modals on other pages appear uneffected.

**Additional context**
- Animations associated with touch events _do_ fire (e.g. subtle colour changes on cancel or close buttons).
- Keyboard interaction remains possible (`esc` to close)

**Comment by MrYuion** [comment]
Hmm... that's a weird one. The action buttons are the same for every for new/edit modal.

**Comment by kimburgess** [comment]
Still occurring in [`build-alpha`@5a53d5f](https://github.com/PlaceOS/backoffice/commit/5a53d5f0c76f6d4044639a4f9cfbbe75512d1b26). It appears to be associated with touch events. With an external mouse attached, interaction is possible via the pointer, however touch events result in behaviour above.

**Comment by MrYuion** [comment]
Yeah, the issue is that click events aren't being thrown by the browser for just those use cases of that model..

**Comment by MrYuion** [comment]
Fixed the issue. Binding to window events prevented the click events firing for some reason.
