### ISSUE TITLE
Display module description on the module list

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#164]
This is because you might have 30 of the same device in the system and the description is the only way to tell them apart.
Example of this in Engine
![image](https://user-images.githubusercontent.com/368013/111418049-116b5880-873b-11eb-8e92-3887a257c944.png)

I configured engine backoffice to display the first line of the description field without overflow and an ellipsis if the cell became small

**Comment by MrYuion** [comment]
That should be fixed now.
