### ISSUE TITLE
Add schema support to JSON/YAML inputs

### ISSUE THREAD

**Issue by MrYuion** [PlaceOS/backoffice#165]
I'd like to add support for JSON schemas into the editor in backoffice.

This would allow us to:

- Show auto-complete for predefined key names
- Validate the of structure and types
- Show details about keys in hover tooltips

@stakach, @kimburgess @caspiano, let me know your thoughts on this.

**Comment by kimburgess** [comment]
Huge +1. This would make settings significantly more discoverable for users. From what I can see in PlaceOS/driver, information needed to generate those schemes is not currently exposed in the driver metadata so this would likely require some effort there, but there's definitely an immediate use case.

**Comment by caspiano** [comment]
As discussed, I think this is a great idea!

Most of the information is there and I don't see any particular hurdles in implementing this.
Given the validation capabilities of JSON schema, we could hack together a DSL of JSON schema validations and pass validations as args to settings definitions.

**Comment by caspiano** [comment]
I can imagine the validations/schema for settings providing excellent context to the autogenerated docs of drivers as well!
