### ISSUE TITLE
Unclear interaction for Metadata editing

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#166]
Currently when metadata is shown, interaction options are not clear for how to view or edit the metadata content.

![2FB4981A-0474-409F-9F6C-CECA3198E725](https://user-images.githubusercontent.com/843652/111705930-2ce67880-888d-11eb-8983-036eda935364.png)

Clicking on the metadata key opens a modal for editing the key/description. In order to edit the metadata itself, the background of the element needs to be clicked or tapped. To aid in discoverability, visual indication of this would be a significant usability improvement.

_Note:_ this same pattern may appear elsewhere in the UI - this is just a specific case that has caused issue with new users. Would be nice to solve this generally if used elsewhere.

**Comment by MrYuion** [comment]
@kimburgess, I've made a tweak to this. Let me know if it's better.

**Comment by kimburgess** [comment]
That's definitely an improvement!

From an initial view, it strikes me as a little confusing having the edit icon (pen) pop open the metadata settings, rather than presenting the metadata itself for editing. Given the majority of interaction and editing will be with the metadata content, rather than it's configuration it may be worth switching that around so that it presents as the primary interaction.

I'll close this off for now though with that base update in place. Items like above are potentially better grouped into the general UX overhaul.
