### ISSUE TITLE
Cannot edit Staff API tenant

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#170]
Once a Staff API tenant has been defined, there is no ability to edit this configuration. This is required is credentials need to be updated.

![74858BC2-B694-4238-99E4-09388E982A5C](https://user-images.githubusercontent.com/843652/113107364-2f5eb000-9247-11eb-9648-2ec014dafb32.jpeg)

**Comment by MrYuion** [comment]
@kimburgess, I don't think there is an API endpoint for edits.

**Comment by kimburgess** [comment]
That does seem to be the case.

https://github.com/place-labs/staff-api/issues/32

**Comment by jeremyw24** [comment]
https://github.com/place-labs/staff-api/issues/32 is resolved, so this issue can progress.
