### ISSUE TITLE
Backoffice: Zones is not displaying all the levels on UI 

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/backoffice#174]
**Describe the bug**
Zones is not displaying all the levels imported on UI 

**To Reproduce**
1. Import few 100 levels using CSV imported
2. Click on Zones menu option on Backoffice page
3. Scroll down to the maximum allowed limit
4. Verify if all the records imported are displayed

**Expected behavior**
Application should allow user to scroll to the last record available

**Actual behavior**
Application limits the user to scroll up to certain level and does not go beyond 

**Screenshots**
![image](https://user-images.githubusercontent.com/83044454/115797832-33ca5300-a418-11eb-84da-6d25576bfd9a.png)

**Desktop (please complete the following information):**
 - OS: WinOS
 - Browser: Chrome
 - Version: NA

**Additional context**

**Comment by MrYuion** [comment]
Fixed in commit e9f7af6b
