### ISSUE TITLE
Desk import failing due to unknown reason 

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/backoffice#175]
**Describe the bug**
Desk import failing due to unknown reason 

**To Reproduce**
1. Prepare desk import data with all relevant level information (use existing levels or import valid level info first)
Note: Use levels which are not displayed on Zones UI
2. Import the desk CSV
3. Verify import outcome / error message

**Expected behavior**
Application should import the desk data and display success message

**Actual behavior**
Import is failing due to some unknown reason. 
Note: It may be when the user uses levels which are not displayed on Zones UI. 

**Screenshots**
![image](https://user-images.githubusercontent.com/83044454/115798493-ba336480-a419-11eb-99c5-2742c9d2a962.png)

**Desktop (please complete the following information):**
 - OS: WinOS
 - Browser: Chrome
 - Version: NA

**Comment by MrYuion** [comment]
Zone requests are paginated. 
I'm guessing that you're not looking through all the pages of zones to check for that level zone.
You can either pass`limit` to the request to up the page size or use next returned by the query to request further pages.

**Comment by s-kadrolli** [comment]
I am not sure if I understand. Can you call me to discuss this?

Best Regards,

Shiv Kadrolli
Senior Consultant
Australia | Project Services
NTT

M: +61 451 979 343
E: ***@***.******@***.***>
hello.global.ntt


P please consider the environment before printing this email

**Comment by s-kadrolli** [comment]
How do I access all the pages of the zones? I am able to search for the level but not able to scroll to it. Secondly, there is no next page option on Zones
I am guessing you are referring to screen shot. The issue is not on the screen above, it was just to show that the level record is available but the data import for the record is failing due to some unknown reason. If the level data is available, then desk import for the level should be successful right?

**Comment by MrYuion** [comment]
Updating `@placeos/ts-client` to `3.7.6` should fix the `next` value returned by the query.
To get all the zones it's probably easy to make the request like this `queryZones({ type: 'level', limit: 10000 })`.
If you want to use next it would be something like this:
```
let resp = await queryZones({ type: 'level' }).toPromise();
let levelZone = resp.data.find(_ => _.name === '<zone_name>');
while(!levelZone && resp.next) {
     resp = await resp.next().toPromise();
     levelZone = resp.data.find(_ => _.name === '<zone_name>');
}
```

**Comment by s-kadrolli** [comment]
I am not referring to query at all. I am trying to upload / import desk metadata CSV from 'populatemetadata' URL. But the import of that file is failing - the issue is around this.

**Comment by MrYuion** [comment]
That page has been written on your end so you'll need to get on to your team about that.
