### ISSUE TITLE
CSV file has successfully imported in PlaceOs Back Office where Neighbourhood metadata has duplicate value ‘ICT’

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/backoffice#176]
**Describe the bug**
CSV file has successfully imported in PlaceOs Back Office where Neighbourhood metadata has duplicate value ‘ICT’

Steps to reproduce:
1.	Edit the desk csv file, duplicate the neighbourhood metadata value ‘ICT’
2.	Upload the file
3.	The file was successfully uploaded

Screenshot: 
![image](https://user-images.githubusercontent.com/83044454/115807926-d12f8200-a42c-11eb-8da2-d7cc7aecb62c.png)

Actual Result: Duplicate metadata value is not allowed when adding or editing a metadata manually, but when CSV file contains duplicate metadata value for neighborhood is successfully loaded. 

Expected Result:  When CSV file contains duplicate metadata value for neighborhood it should not successfully loaded. An error message should be displayed. It should behave the same with other metadata (e.g. tech, features etc.)

**Comment by MrYuion** [comment]
Hmm... that's valid JSON, I'm not seeing an issue there.
I'm not receiving any errors with the data formatted in that way.

**Comment by s-kadrolli** [comment]
Can we discuss before the issue is closed? Ideally the person who has logged the defect closes it. 

We are referring to duplicate values allowed by PlaceOS. There should be a validation if duplicate value or any value for that matter

**Comment by MrYuion** [comment]
The field is just stores raw JSON. If you want validation you will have to perform it before upload the data.

**Comment by s-kadrolli** [comment]
I agree to an extent, however, I will leave it to Suncorp if they are okay with this. Can you please leave this open
