### ISSUE TITLE
Updating Code in Zone Edit modal will be allowed to save, but the original value will still be displayed in the edit screen

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/backoffice#177]
Updating Code in Zone Edit modal will be allowed to save, but the original value will still be displayed in the edit screen.
Steps to reproduce:
1.	Navigate to any Zone with existing Code value (ex. nine9)
2.	Click ‘About’ tab
3.	Click edit 
4.	From ‘Code’ field update the Code value to different value (ex. MyCode)
5.	Click ‘save’> Successfully saved > Code is updated in the ‘About’ screen
6.	Click edit 

Screenshot:

![image](https://user-images.githubusercontent.com/83044454/115807995-f3290480-a42c-11eb-9c46-1a0fdbc0a4e6.png)

Actual Result: Code field = nine9
Expected Result:  Code field = MyCode

**Comment by MrYuion** [comment]
Fixed in latest build
