### ISSUE TITLE
Updating Type in Zone Edit modal will be allowed to save, but the original value will still be displayed in the edit screen.

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/backoffice#178]
Updating Type in Zone Edit modal will be allowed to save, but the original value will still be displayed in the edit screen.
Steps to reproduce:
7.	Navigate to any Zone with existing Type value (ex. nine9)
8.	Click ‘About’ tab
9.	Click edit 
10.	From ‘Type field update the Type value to different value (ex. MyType)
11.	Click ‘save’> Successfully saved > Code is updated in the ‘About’ screen
12.	Click edit 

Actual Result: Type field = nine9
Expected Result:  Type field = MyType 

Screenshot:
![image](https://user-images.githubusercontent.com/83044454/115808041-105dd300-a42d-11eb-8b9a-311af6c875f2.png)

**Comment by MrYuion** [comment]
Fixed in latest build
