### ISSUE TITLE
The Metadata that was manually added was saved in one single line – Appended by ‘backlash’

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/backoffice#179]
The Metadata that was manually added was saved in one single line – Appended by ‘backlash’
Steps to reproduce:
1.	Select any zone 
2.	Click Metadata tab
3.	Click ‘Add new Metadata Field’
4.	Copy the sample Jason file from https://confluence.int.corp.sun/confluence/display/BHQ/Desk+Metadata
5.	Paste it to the metadata field and click save

Actual Result: The metadata is saved in single line and  each data was appended by backslash
Expected Result:  The json should be save in readable format.

Screenshot:

![image](https://user-images.githubusercontent.com/83044454/115808136-426f3500-a42d-11eb-84c9-d4a9e5ee2300.png)

**Comment by MrYuion** [comment]
Fixed in latest build
