### ISSUE TITLE
add support for zone parent selection

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#18]
Zones can now have parents

* field name is `parent_id` - so could you please add a zone dropdown in new and edit
* Have a tab for viewing the children of a zone - same as the get a list of zones request with the param `parent=zone-parent-id`

Please filter out the current zone_id from the results when showing that zone. As we don't want a zone to be its own parent

**Comment by MrYuion** [comment]
How will circular dependencies work?

**Comment by stakach** [comment]
circular dependencies are fine as it's mainly just a child parent relationship thing - so shouldn't be too much of an issue.
Just up to anything consuming the API to protect against it (if they are walking the entire parent-child tree)

**Comment by stakach** [comment]
The request for sub-zones is a bit off:
* lets say we have a zone-1234 that has a parent zone-5678
* when viewing zone-1234 we want to query for children: `/zones?parent=zone-1234`

However currently when viewing zone-1234 it's querying: `/zones?parent=zone-5678` so it's presenting the current zone as a child

**Comment by stakach** [comment]
The child zone count is also off

<img width="350" alt="image" src="https://user-images.githubusercontent.com/368013/78009649-0df58a80-738d-11ea-9124-70d29eb2c408.png">

**Comment by MrYuion** [comment]
Yeah, I've already made a fix for those. Should be in the next build.
