### ISSUE TITLE
Application prompts user with a question without an option to respond

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/backoffice#181]
Application prompts user with a question without an option to respond.

Steps to reproduce:
•	Add a new column to the Import file
•	Upload the file
Expected Result: Either the message should be reworded to inform the user or add option so that user can respond to the query posted. 
Actual Result: When an extra column is added even with spaces, getting the below error. There is a question being posed here, but there is no YES/NO option. Or to upload the file in this case.
Secondly, unless user refreshes the page, error is not cleared.

Screenshot:
![image](https://user-images.githubusercontent.com/83044454/115808496-ebb62b00-a42d-11eb-86c6-47b78c1db269.png)

**Comment by MrYuion** [comment]
This is an issue with the code written by your team. Not an issue with backoffice.
