### ISSUE TITLE
Invalid / negative values accepted in all fields except for level name field where empty value are accepted

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/backoffice#182]
**Describe the bug**
Invalid / negative values accepted in all fields except for level name field where empty value are accepted

Application allows any character except Null value in the level column. Field validations should be defined for each field as per Suncorp requirements

Screenshot:
Test data:
![image](https://user-images.githubusercontent.com/83044454/115809307-2ff5fb00-a42f-11eb-8acf-92acbcd94af3.png)

![image](https://user-images.githubusercontent.com/83044454/115809478-85caa300-a42f-11eb-986c-e9f3bae217e8.png)
![image](https://user-images.githubusercontent.com/83044454/115809483-895e2a00-a42f-11eb-86e2-809b75dc108f.png)

The below screenshot captures the error where application displays error message in case of NULL value
![image](https://user-images.githubusercontent.com/83044454/115809324-36847280-a42f-11eb-99bf-2dc1a50f443d.png)

**Comment by MrYuion** [comment]
Those are valid strings. I don't see any reason to strip out various characters.
All the values are sanitised on the backend, so I'm not sure this is an issue.

**Comment by s-kadrolli** [comment]
Looks like junk data, this should be defined by /aligned with Suncorp requirements to allow or not to allow such characters. Please keep this open for Suncorp to review and respond
