### ISSUE TITLE
'Error loading calendars data' error is displayed post refreshing the page

### ISSUE THREAD

**Issue by s-kadrolli** [PlaceOS/backoffice#183]
Error loading calendars data' error is displayed post refreshing the page

Steps to Recreate:
1.	Navigate to ‘Workplace | PlaceOS’ screen and click on refresh button
2.	System is throwing an error as "Error loading calendars data' 

Expected Result: Only valid error messages should be displayed

Actual Result: Irrelevant error message displayed 

Screen Shots:
![image](https://user-images.githubusercontent.com/83044454/115809567-b1e62400-a42f-11eb-9028-719d9d5255aa.png)

**Comment by MrYuion** [comment]
Not a backoffice issue. Please don't pollute the backoffice with issues from other systems.

That's issue is due to either the Staff API not being setup in your environment or your user not having a calendar in the client's Office365/Google system
