### ISSUE TITLE
Repository types do not show

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#185]
When viewing a respository, the type does not show.

![A907285B-8B86-41AB-B896-E4CFAA39627A](https://user-images.githubusercontent.com/843652/117103584-f2de2100-adbd-11eb-8676-ea00d28ebee6.jpeg)

Appears to be due to:
https://github.com/PlaceOS/backoffice/blob/20c6e03f9194f95df5ac471fae4c99a4ee7aedc6/src/app/repositories/repository-about.component.ts#L34

Types are lower case.

**Comment by MrYuion** [comment]
Fixed in 10a54205
