### ISSUE TITLE
Systems > Modules: previously selected function is still displayed when a different Module is selected

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#189]
When selecting a module from the systems page and then any of it's functions (a),
then selecting a different module, the drop down list of available functions still includes function a at the top, even though that function is NOT available for this selected module.

the drop list of available functions should ONLY list functions that are available for the selected module. NOT any functions from a previously selected module

**Comment by w-le** [comment]
thanks alex, so does that change affect the list of functions when a different Module is selected but the System is the same? That's the situation I was trying to describe

i.e. the user has NOT switched Systems. ONLY switched Modules

**Comment by MrYuion** [comment]
@w-le, it is affected by the module changing.
