### ISSUE TITLE
Zone metadata display and editing from backoffice

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#19]
Documentation: https://placeos.docs.apiary.io/#reference/0/zones/get-zone-children-metadata
(Get and update metadata, not listed there is a delete - same as update just with delete verb)

Currently blocked by PlaceOS/rest-api#13

**Comment by MrYuion** [comment]
There isn't a create. Is that just the same as update?

**Comment by stakach** [comment]
Yep, update and create are the same thing.
It's a complete replace every-time based on the name. You can ignore the `id`

**Comment by stakach** [comment]
This should now be in the latest docker image

**Comment by stakach** [comment]
Almost there, creating new metadata works but when you click save is goes like this:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/368013/78108490-3c35a180-7443-11ea-997f-8b5881f7a124.png">

After a refresh the correct metadata is there, which is good.
Also missing a delete button, same route as save - just with a delete verb

**Comment by stakach** [comment]
Nice, looking good
