### ISSUE TITLE
extensions > zone > Area editor: allow closed polygons, not just rectangles

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#192]
extensions > zone > Area editor: allow closed polygons, not just upright rectangles

**Comment by MrYuion** [comment]
@w-le, can you move this to https://github.com/PlaceOS/frontend-tools
That's the repo that contains the logic for that UI.

**Comment by w-le** [comment]
https://github.com/PlaceOS/frontend-tools/issues/1
