### ISSUE TITLE
Repositories view attempts to query driver endpoints for interface repos

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#194]
**Describe the bug**
When the repositories view loads, a query is made to `/api/engine/v2/repositories/:id/drivers` for all repository types. This endpoint is only available on driver repositories.

**To Reproduce**
1. Go to 'Respositories'
2. Click on and interface repository.

**Expected behavior**
Queries to `/api/engine/v2/repositories/:id/drivers` should only take place if `:id` refers to an driver repository (available from `/api/engine/v2/repositories/:id`.

**Comment by MrYuion** [comment]
Looks like a some point the values for the changed to lower case from upper case on the first character.

**Comment by kimburgess** [comment]
That is correct. I think there may be a few places where this change has not been fully coordinated. As of crystal v1.0.0 enum serialisation will appear in `underscored_lowercase` form. For impact here, this applies to `rest-api` service versions v1.25.0 and above, or platform releases from `placeos-1.2104.0` and later.

This applies to any fields containing enum types which serialise to their string form. Across the API these values are single words so while overall structure has not changed, cases will have. If parsing of these is case sensitive (which is completely reasonable) this forms a breaking change. Parsing in the opposite direction (e.g. when POST to PlaceOS endpoint, or interacting with the websocket) is _not_ case sensitive, but is likely worth aligning neatness.

**Comment by MrYuion** [comment]
Everything else seems to be `underscored_lowercase` so it should be fine now.
