### ISSUE TITLE
Module debug window does not flush history

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#195]
**Describe the bug**
When subscribed to debug messages, the in browser state keeps all received messages. This leads to growing resource usage over time if a window is kept open.

**Expected behavior**
A FIFO buffer that keeps _n_ most recent lines should be used.

**Comment by MrYuion** [comment]
Fix for this should be good to go.

**Comment by kimburgess** [comment]
Due to my rather non-frontend friendly setup (iPadOS only), I'm probably not the best one confirm resolved - might need to give another member of @PlaceOS/ui a prod if you'd like a second set of eyes before closing.

For tracking though, can you swing a link into here with the PR / commit where this was addressed?

**Comment by MrYuion** [comment]
42696d7, b624cec, 65dfef6e were the commit that made changes effecting this issue.
