### ISSUE TITLE
Driver > settings > unencrypted is rendered as json instead of YAML

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#196]
Driver > settings > unencrypted is rendered as json instead of YAML

but it should be redenered as YAML, same as the the Merged tab

**Comment by MrYuion** [comment]
Is the data coming down from the backend as JSON?

**Comment by w-le** [comment]
Yes looks like response `settings` has `settings_string` as JSON when the issue is present.
In other drivers where the issue not present, `settings_string` is YAML.

So to me that seems like it's a backend issue for placeos/rest-api, would you agree @stakach ?

**Comment by stakach** [comment]
Backend technically only deals in JSON so the ideal situation would be:

1. before saving the settings when adding a new driver convert them to YAML first and then save them
2. we should move to defaulting to encryption - so can we by default save the settings in the `Support` tab
