### ISSUE TITLE
Repositories: Doesn't show branch selector when is a driver

### ISSUE THREAD

**Issue by cacique-coder** [PlaceOS/backoffice#202]
Repositories: Doesn't show branch selector when is a driver

HEAD (2fbe7be7) 
branch: build/dev.

Returning commits via API is successful

**Comment by MrYuion** [comment]
@caspiano, is this available on the backend?

**Comment by caspiano** [comment]
@MrYuion the latest platform versions, `>= v1.2105.2`, should support branch switching.
Note: We're in the process of creating a `v1.2107.0` release that should be out in the next few days.

**Comment by MrYuion** [comment]
It should be fixed in the latest build.
