### ISSUE TITLE
feat: dynamically construct support url

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/backoffice#207]
**Is your feature request related to a problem? Please describe.**
Entering support URL manually is time consuming, the necessary data is available to construct this automatically.

**Describe the solution you'd like**
Dynamically set the system Support URL, suggest drop downs that select the base domain, the path to the intended UI and the system ID.

**Comment by MrYuion** [comment]
`{{<prop_name>}}` will be replaced with the relevant value in the added URL.
e.g. `https://panel.it/#/{{id}}` would become `https://panel.it/#/sys-1234`.
