### ISSUE TITLE
Start and stop driver weirdness

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#21]
<img width="208" alt="image" src="https://user-images.githubusercontent.com/368013/77921154-1c8b6580-72eb-11ea-9a59-2d086f13b95a.png">

When clicking toggle on a **running and disconnected** module, it calls start and notifies that stop was successful.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/368013/77921311-52304e80-72eb-11ea-9053-bfcbe3c31da3.png">

Experimentally it seems to be toggling based on `connected` status, versus the running state (where it should be using running state as the only indicator)

The notification always indicates that the module was stopped no matter if it calls start or stop.

**Comment by stakach** [comment]
Thanks for the update, stop and start behaviour now looks correct
The alert still says stopped no matter what action is taken

**Comment by MrYuion** [comment]
I've already made a fix for that. Should be in the next build.
