### ISSUE TITLE
domains > applications > new application: add frontend validation to auto remove any whitespace in redirect_uri

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#212]
domains > applications > new application: auto remove any whitespace in redirect_uri

a very common issues that end users face is that they paste in a redirect_uri and it has a space at the end, causing the resulting client_id to be incorrect. This is pretty difficult for them to identify as an error.

Since we know that redirect_uri needs to be a valid URI, can you strip any trailing whitespace before making the POST?
OR show a validation error to the user when they click Save.

**Comment by jeremyw24** [comment]
Error seems sufficient when there is whitespace now and prevents save.

@w-le

**Comment by w-le** [comment]
almost there,
1. I think the url validation needs to also accept port numbers
![image](https://user-images.githubusercontent.com/10395560/130171723-be419bd4-cf74-4d0c-8512-565fc2380d82.png)
and localhost
![image](https://user-images.githubusercontent.com/10395560/130171796-a3233d16-fd94-4f01-bc6c-e15329bedfeb.png)

2. a minor unrelated issue is that when "skip authorization" is not ticked, the POST will have it's param as a string instead of a bool, resulting in a correct 400 response
![image](https://user-images.githubusercontent.com/10395560/130172182-7a03e734-aeca-4ca1-9095-d87563a54d80.png)

**Comment by MrYuion** [comment]
@w-le, any hostname should work as long as it has two parts. `first.second`

**Comment by w-le** [comment]
I think there will be many scenarios where a single part hostname will need to be added, specifically when testing on a local network (e.g. a mobile device connects to the server locally).

So i believe we will need to support single part hostnames as valid.
