### ISSUE TITLE
Setting merge UI behaviour differs from backend behaviour

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#216]
**Describe the bug**
When viewing merged settings that combine config from different encryption levels the merge behaviour used by Backoffice differs to that of the backend. 

Currently the backend applies a [shallow merge](https://github.com/PlaceOS/models/blob/9426c230842bb1aadfda51d861da89e511f050bd/src/placeos-models/module.cr#L216-L224), wheres Backoffice uses a deep merge.

**Expected behavior**
Merged settings views should match across all system components.

**Additional context**
Some potential future complexity exists in this area via https://github.com/PlaceOS/core/issues/86. To reduce fragility if this, or other similar changes it is likely worth ensuring settings merge behaviour takes place on the backend only.

**Comment by kimburgess** [comment]
@MrYuion what build(s) is this available on? I'll give it a spin.

**Comment by MrYuion** [comment]
Should be on the latest dev build.

**Comment by kimburgess** [comment]
Confirming this is matching current backend behaviour.

Both components now perform a shallow merge with [settings at higher encryption levels prioritised](https://github.com/PlaceOS/models/issues/119).

**Comment by kimburgess** [comment]
@MrYuion it looks like this may only be available on `build/dev` currently. Can you please confirm here when available on `build/prod` by re-closing this issue.
