### ISSUE TITLE
Invalid regex pattern

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#227]
Pattern recently added for form validation contains unescaped characters.
 https://github.com/PlaceOS/backoffice/blob/421268800676602fb25de919bf269b45cc4d16b7/apps/backoffice/src/app/domains/applications.utilities.ts#L6
 
 For usage in JS, this should be 
 ```
 ^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?
 ```

**Comment by MrYuion** [comment]
Hmm... it doesn't like that either.
