### ISSUE TITLE
Display Settings history

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#228]
Add new subsections in backoffice that allow the user to see Settings history for the currently selected driver/module/system/zone:
`/api/engine/v2/settings/{settings-id}/history`

**Comment by MrYuion** [comment]
Hmm... getting 404 for that endpoint.

**Comment by w-le** [comment]
Damn which version of rest-api?

**Comment by MrYuion** [comment]
Nevermind, I worked out that issue.
