### ISSUE TITLE
ensure page elements are not draggable, as it annoyingly causes the drop target to appear 

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#230]
many times when using the mouse myself and others have inadvertently caused the drag-drop target to appear, just by attempting to click a ui element like a tab. there is no way to remove the drop taget afterwads so we all have to refresh our page. very annoying as navigation is sometimes lost for non-deeplinked pages.

please make these items non-draggable because there is no use case.

while you're there, please also remove the scrollbar from the LHS navbar, as it partially obscures the icons and looks unprofessional. just let it scroll without a scrollbar 

![image](https://user-images.githubusercontent.com/10395560/132442912-561ebc98-1412-4dc4-9dd4-754acd1ca771.png)

**Comment by caspiano** [comment]
Yep, have noticed this too

**Comment by MrYuion** [comment]
Should be fixed in the latest.
