### ISSUE TITLE
After selecting text from page body, ctrl+c shortcut does not copy to clipboard

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#232]
After selecting text from page body, ctrl+c shortcut does not copy to clipboard
this is always reproducible and affects other apps like driver test harness log output txt box
For example, try to ctrl+c the System NAME from the Systems page.

Win10 Chrome latest

Note that when text from a text BOX is selected (instead of from the page element), that the ctrl+c shortcut works fine.

**Comment by jeremyw24** [comment]
Confirmed this is now working in dc80f8c | Built: 13/09/21 at 12:23PM
