### ISSUE TITLE
Provide visibility of system availability issues

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#235]
**Is your feature request related to a problem? Please describe.**
The usage of a service worker and caching behaviour this provides often leads to obscuring issues that may be indicative of wider system faults. This is primarily evident on development environments, but also applies to production instances. As the primary management interface, this is not desirable.

**Describe the solution you'd like**
When the API service is unavailable, this should be clearly indicated. Common failure modes witnessed in the wild:
- no backend services available (requests to all paths failing)
- no authority registered for the request domain (request to `/auth/authority` returning 404)
- main API service unhealthy (requests to `/api/engine/v2/` returning 500)

**Describe alternatives you've considered**
Removal of service worker to allow default browser behaviour (likely undesirable due to other impacts).

**Additional context**
Failure modes for _user_ interfaces should **not** follow this behaviour as UX requirements there are different (e.g. a scheduling interface may be able to continue to provide reduced functionality with cached information during minor outages). Notes above specific to Backoffice only.

**Comment by caspiano** [comment]
Closed in [c8fc623](https://github.com/PlaceOS/backoffice/commit/c8fc62371037582149dc0ea2eeb440b015b17387)
