### ISSUE TITLE
Newly added modules at the top of the list

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#24]
Adding a module to a system causes it to appears at the top of the list.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/368013/78111735-d21ffb00-7448-11ea-98d6-7c10b30d8d8f.png">

After Selecting another system and then coming back or refreshing, then the module is at the bottom of the list, where it should be.

**Comment by stakach** [comment]
Looking good :)

**Comment by stakach** [comment]
Actually it seems if I do the following:

1. add a new driver
2. go to the `about` tab
3. go back to the `drivers` tab

The new driver(s) are now at the top of the list and executes then route incorrectly.

**Comment by MrYuion** [comment]
Should be fixed in the latest build

**Comment by stakach** [comment]
thanks!
