### ISSUE TITLE
Listing authentications for a domain

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#244]
source issue: https://github.com/place-technology/suncorp-ntt/issues/178

the issue here is that when authentication sources are requested, only one request is made:

/api/engine/v2/oauth_apps?authority=authority-1234
However there needs to be 3 requests, with the results merged for that list.

/api/engine/v2/oauth_apps?authority=authority-1234
/api/engine/v2/saml_apps?authority=authority-1234
/api/engine/v2/ldap_apps?authority=authority-1234
Also when a new auth is added, can it be added to the existing list

**Comment by stakach** [comment]
Can replicate on our dev server
https://placeos-dev.aca.im/backoffice/#/domains/authority-GAdySsf05mL/authentication

The requests made when a domain is selected: (only `oauth_apps`)
![image](https://user-images.githubusercontent.com/368013/148877310-0800eea9-95ef-4af2-b737-14eb25493c72.png)

**Comment by MrYuion** [comment]
Looking at it on our server there is a 500 error which prevents future requests.

**Comment by MrYuion** [comment]
@stakach, looking at the 500 error from the SAML endpoint it returns:
```
ERROR: Missing param name: "authority_id" (KeyError)
  from usr/share/crystal/src/hash.cr:1034:28 in '[]'
  from app/src/placeos-rest-api/controllers/authentications.cr:5:3 in '->'
  from app/lib/action-controller/src/action-controller/router/route_handler.cr:32:7 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from usr/share/crystal/src/http/server.cr:500:5 in '->'
  from usr/share/crystal/src/primitives.cr:266:3 in 'run'
  from ???
```

**Comment by stakach** [comment]
I found the bug fyi https://github.com/PlaceOS/rest-api/commit/67f3cb8e5cdd7f4acba5f317df608c2f72f42f8e
took me a moment to notice the missing `?`
