### ISSUE TITLE
Debug console never closes, just goes invisible

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#25]
When closed (even if never opened) the console prevents interaction with anything that would otherwise be obscured by the console at it's default open size.

If you resize it, it still only obscures interactions under where the console would be at its default size.

Bit of a weird one, luckily it's not usually obscuring too much usually but was a strange but as the mouse still changes for the resize hovers (tested in chrome)

**Comment by stakach** [comment]
If you debug something and then close it you can see it's over the content, just invisible

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/368013/78144572-83d81f80-747b-11ea-82f3-5d927e15f45b.png">

**Comment by MrYuion** [comment]
That's fine. I've made it non-interactive.

**Comment by stakach** [comment]
Yeah this is testing with the non-interactive build.
I still can't click on anything below it, the main difference seems to be that the mouse cursor doesn't change when i hover over where the `clear` button is

**Comment by MrYuion** [comment]
It should work in the latest build.

**Comment by stakach** [comment]
Sweet, looking good!
