### ISSUE TITLE
backoffice / domains / applications / add: uri with capitals is seen as invalid

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#253]
backoffice / domains / applications / add: uri with capitals is seen as invalid

But the capitals are required, for Chronograf SSO

change URI validation to accept capital letters

![image](https://user-images.githubusercontent.com/10395560/155288163-e55cc516-64c0-4e95-b676-8d19a3e80b1a.png)

**Comment by jeremyw24** [comment]
@MrYuion is this resolved?

**Comment by MrYuion** [comment]
It should be.
