### ISSUE TITLE
Restrict `Interface` repositories to releases

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#255]
**Is your feature request related to a problem? Please describe.**

After https://github.com/PlaceOS/frontend-loader/pull/47, interfaces need to be restricted to releases.
We need to be able to support mutable tags that map to releases, such as `latest` and `development`.

We may need to create a release per platform release.

**Comment by MrYuion** [comment]
Is it possible that we can allow for either?
Where the release on can just link to an archive file.

**Comment by tassja** [comment]
Releases in the api: https://github.com/PlaceOS/frontend-loader/blob/2ec2ee367af1f980b27de05889fe47ab2fb6dcab/src/placeos-frontend-loader/api/repositories.cr#L58-L65

**Comment by caspiano** [comment]
@tassja, @MrYuion needs to be able to fetch the releases from the public API

**Comment by tassja** [comment]
@MrYuion added an endpoint in rest-api [here](https://github.com/PlaceOS/rest-api/pull/262)

**Comment by MrYuion** [comment]
@tassja, what does the response look like for that endpoint?

**Comment by tassja** [comment]
Returns an array like this `["v4.9.0", "v4.8.5", "v4.3.7", "v4.3.6", "v4.3.2", "v3.3.2", "v3.3.0"]`

**Comment by MrYuion** [comment]
@tassja, am I just passing this value in the commit or branch field of the repo?
