### ISSUE TITLE
Edit Repo: Commits are not listed for selection 

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#261]
g15af01a7 | Built: 19th Apr 2022,  (the latest version that can be pulled from build/dev branch by latest frontend-loader, on [placeos-dev](https://placeos-dev.aca.im/backoffice/#/repositories/repo-Fhyon5PsoYO/about)) on May 1st.

When editing a front or backend repo, the list of available commits is not displayed for selection, even though api responds with commits. The "Repository Commit:" field is always blank and clicking it does not display a dropdown.

Drivers repo
![image](https://user-images.githubusercontent.com/10395560/165898964-5fac3ae2-7e77-4bc0-a85c-d23f79d47bc0.png)

Frontend repo
![image](https://user-images.githubusercontent.com/10395560/165899132-63a16dc0-e13e-4e9f-8e9a-21ae435c3c6c.png)

Notice also that for this frontend repo which is using the old commits selection method instead of new release selection method, the ui still shows a "Release:" selector and has the branch name, where that text field should be labelled "Branch:"

Also, when editing a Driver, there is not Commit selection field displayed:
![image](https://user-images.githubusercontent.com/10395560/165899861-d31ed855-14e8-4a5f-a01b-3eb333a024f7.png)

**Comment by stakach** [comment]
looks like an error parsing the date string
<img width="413" alt="image" src="https://user-images.githubusercontent.com/368013/166079743-36f45ba8-198f-42d2-afdc-0561338a0f66.png">

**Comment by w-le** [comment]
addressed in 11c1364f72b6e07eec30fb24db5a8db60478ac1b
