### ISSUE TITLE
Align look and feel with Portal Frontend

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#262]
**Is your feature request related to a problem? Please describe.**

There is an ad-hoc feel to the backoffice application.
Pages have different component layouts without a common design system.
The sidebar is small, with large icons and truncated text.

The current state of backoffice has not undergone an in-depth review by @candyrusso in a long time and what we have today is the culmination of iterations of immediate necessity leading to an overall lack of cohesion in the interface.

The portal API has breathing room and consistent component layouts.

**Describe the solution you'd like**

Refactor backoffice to share more styling and use a similar layout to the portal frontend.

**Comment by MrYuion** [comment]
Uploading Screen Recording 2022-05-06 at 2.51.32 pm.mov…

**Comment by MrYuion** [comment]
https://user-images.githubusercontent.com/20103948/167322739-cd68d7bd-a157-41e6-8516-b37488cce791.mov

**Comment by caspiano** [comment]
@MrYuion This is great, could you ensure whatever changes you make undergoes a UX review by @candyrusso?

**Comment by MrYuion** [comment]
@caspiano, there is a build of this on `build/feat-layout` branch if you want to try it out.
