### ISSUE TITLE
drag/drop a file to upload to S3 does not show an uploading status toast anymore

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#277]
with the new version of backoffice
[BACKOFFICE][APP] g43df8638 | Built: 24th Jul 2022, 8:22PM

Can test this on placeos-dev by dragging a file in to backoffice.

**Comment by MrYuion** [comment]
Hmm... seems to be working fine for me.
<img width="1054" alt="Screen Shot 2022-08-11 at 1 12 16 pm" src="https://user-images.githubusercontent.com/20103948/184059043-486ef4d9-c46b-45bb-85dd-6ee50a9a1a61.png">

**Comment by w-le** [comment]
looks like that Uploads popup is shown ONLY on the "Manage instances" page and not on any of the other pages e.g. Systems page.

cool i'll move to low pri as there is an easy workaround. not urgent at all

**Comment by MrYuion** [comment]
@w-le should be fixed in the latest

**Comment by w-le** [comment]
thanks i'll get sravani to test then close if confirmed.
fyi sravani this is **lowest** priority
