### ISSUE TITLE
Systems>Modules: While attaining module status, the UI should not show that the module is offline

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#283]
Currently just after the backoffice systems>modules page has loaded and the websockets are connecting, the "connected" status button on the far left of the modules table will appear RED.

RED means offline and that's usually incorrect. The end user will interpret it as the module is offline (as opposed to unknown) and may take an action or call support. This has happened many times.

I propose we add different visual representation to let the user know that the page is still determining the Module status and that the user needs to wait. e.g. a small spinner.

This small change will make a significant improvement to user experience.

**Comment by MrYuion** [comment]
I think this might be backend as the `connected` initial status is based on the value in the API model.

**Comment by w-le** [comment]
hey @stakach what are your thoughts on whether this is something that needs a backend or frontend change? as per alex's comment

**Comment by w-le** [comment]
I see that there's a spinner now and that's fantastic.
The center of the spinner is still a red dot which hints at offline though (which has a red dot icon).
Can we change the whole spinner colour to orange instead?

<img width="40" alt="Screen Shot 2022-09-14 at 11 39 30 pm" src="https://user-images.githubusercontent.com/10395560/190200311-cca5dee2-6f07-45e1-a6ae-788fb2564871.png">

**Comment by MrYuion** [comment]
Made the dot orange on the latest.

**Comment by w-le** [comment]
that's awesome, thanks
