### ISSUE TITLE
Systems page: The debug window at the bottom right no longer shows any debug data from Selected modules

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#285]

**Comment by MrYuion** [comment]
@w-le is the frontend correct sending the debug command down the websocket?
If so is the backend actually sending debug information back up the websocket?

**Comment by w-le** [comment]
yes because I can see all the debug info in JS console. just not in the UI element

**Comment by MrYuion** [comment]
UI element seems to be working fine for me.

https://user-images.githubusercontent.com/20103948/190571908-d52086ac-a11b-4cff-8840-f31ef1975a53.mov

**Comment by w-le** [comment]
I know that the window appears fine, I'm saying that no debug text from the websocket ever gets displayed in there.

**Comment by MrYuion** [comment]
Do you have a module I can test this with?

**Comment by w-le** [comment]
yes exec `rooms` in the Module here while watching js console(url redacted)

remember to enable Info and Verbose logging level

**Comment by MrYuion** [comment]
Fixed in the latest.

**Comment by w-le** [comment]
confirmed, thanks

**Comment by w-le** [comment]
yes because I can see all the debug info in JS console. just not in the UI
element
