### ISSUE TITLE
In any text editor component, when text is selected, the spacing changes. It should not change

### ISSUE THREAD

**Issue by w-le** [PlaceOS/backoffice#286]
<img width="236" alt="Screen Shot 2022-09-16 at 1 11 01 pm" src="https://user-images.githubusercontent.com/10395560/190561250-97d58b6b-1a20-4d4f-81de-472f5290bb3d.png">

when text is selected the spacing changes: very annoying
<img width="281" alt="Screen Shot 2022-09-16 at 1 11 32 pm" src="https://user-images.githubusercontent.com/10395560/190561297-f08a5ce5-bab0-4862-9188-b6a2f4094ea2.png">

**Comment by w-le** [comment]
thanks, note that the issue also impacts other monco fields like metadata and exec result popup

**Comment by w-le** [comment]
the issue resolved but the font is no longer monospace (looks like arial). Can it be changed back to monospace font? Thanks

**Comment by MrYuion** [comment]
That's the default font used by the editor.
The issues was that when I set a custom font it wasn't calculating the correct size of whitespace when it was selected.

**Comment by w-le** [comment]
I'm pretty sure this is not the default font though
(image redacted)
cause even the product web page screenshots show a monospace font (which should obviously be used instead of variable space if we're showing json and yaml)
https://microsoft.github.io/monaco-editor/

**Comment by MrYuion** [comment]
Worked out the issue. Fixed in latest.

**Comment by w-le** [comment]
confirmed, thanks
