### ISSUE TITLE
Add existing module list details

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#3]
- This list needs the details (IP or URI) displayed in the same way as the modules tab
- logic modules should not appear on this list (as they can only exist in a single system)
- How does searching work? I can't seem to filter using IP address for instance

<img width="369" alt="image" src="https://user-images.githubusercontent.com/368013/77039761-b826f700-6a0a-11ea-8a16-0e345507818b.png">

**Comment by MrYuion** [comment]
Is there a way to filter out logic modules?
Searching just uses the `q` param.

**Comment by stakach** [comment]
Ahh it doesn't actually perform the search at the moment.
If you add `?no_logic=true` should filter them out

**Comment by stakach** [comment]
Looking good!
