### ISSUE TITLE
Parse the values before displaying module state

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#31]
Basically it would be a waste of processing to parse each value on the server-side (as the main purpose of this API is debugging)
So before displaying the state can you parse each keys value?

![image](https://user-images.githubusercontent.com/368013/78763425-79141200-79c8-11ea-8398-e7f86ddb3fa7.png)

**Comment by MrYuion** [comment]
Hmm... I'm already doing that on the frontend.

**Comment by stakach** [comment]
What I mean is that this request basically spits out what is in redis. So it's sending

```
{
"key1": "json string of value",
"key2": "json string of value2",
}
```

So the `"json string of value"` should be parsed
something like

```
status = {};
JSON.parse(response.body).each(function(key, value) {
   status[key] = JSON.parse(value);
});
```

**Comment by stakach** [comment]
woot
