### ISSUE TITLE
Create New User -> Name is Blank

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#37]
**Describe the bug**
Creating a new user in Backoffice, after saving the user is created but the name is blank.

**To Reproduce**
1. Go to users.
2. Add new user.
3. Enter required details, name, email etc.
4. Save new user
5. New user will appear in the user list with no name

**Expected behavior**
Username should be shown in the user list and when inspecting the user.

**Screenshots**
![Screen Shot 2020-04-20 at 3 06 57 pm](https://user-images.githubusercontent.com/44023728/79715986-9cb85000-8318-11ea-9915-a2f8ed8b1500.png)

**Comment by MrYuion** [comment]
This works on the latest build.
https://drive.google.com/file/d/1X0VtZH27BmhK0o-vjQYBZstDuP8-id2S/view?usp=sharing

**Comment by jwest-aca** [comment]
Issue is still present on pwc dev instance, suggested backend error @stakach 

http://pwcme.dev.place.tech/backoffice/#/users/-/about

**Comment by stakach** [comment]
old version of backoffice that is sending empty fields to the backend which is setting first and last name fields as blank and then the backend uses those blank fields in priority over the name field which is then set to blank

Updating to the latest version of backoffice will resolve the issue

**Comment by MrYuion** [comment]
The issue still occurs when the fields are not present.

**Comment by jwest-aca** [comment]
pwc dev is up to date both for placeos and backoffice front end, issue still present.

**Comment by MrYuion** [comment]
<img width="542" alt="Screen Shot 2020-04-22 at 3 06 16 pm" src="https://user-images.githubusercontent.com/20103948/79943158-85f63280-84ab-11ea-95df-e1811b9c6a60.png">
<img width="545" alt="Screen Shot 2020-04-22 at 3 06 23 pm" src="https://user-images.githubusercontent.com/20103948/79943162-8a225000-84ab-11ea-81b3-b6ec123955d9.png">

**Comment by stakach** [comment]
It works now for new users: http://pwcme.dev.place.tech/backoffice/#/users/user-EopbHAp4YUw/about
Just that old user had the `first_name` and `last_name` set
Those fields exist for SSO and override whatever is in `name`

So all good for all new users, delete the old one and you'll be laughing
