### ISSUE TITLE
Users -> Edit User Generates Error

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#38]
**Describe the bug**
Editing a user to add the username after creation causes an error when saved. 

**To Reproduce**
1. Go to users
2. Edit a user
3. Change/Enter something in the name field
4. Save
5. Error

**Expected behavior**
User should save with updates.

**Screenshots**
![Screen Shot 2020-04-20 at 3 09 52 pm](https://user-images.githubusercontent.com/44023728/79716134-14867a80-8319-11ea-81ed-b9668ae431b2.png)

**Comment by MrYuion** [comment]
This works on the latest build.
https://drive.google.com/file/d/1ilB_Qt6YXJIcqSX204wuslW1AzM5_gZe/view?usp=sharing
