### ISSUE TITLE
Drivers -> Date on Commit

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#39]
**Describe the solution you'd like**
Is it possible to a show a date with the commit hash to make it easier to identify, having to correlate with the hash to find the latest is not ideal. 

**Describe alternatives you've considered**
Having the commit selector to default to the most recent if no commit is selected?

![Screen Shot 2020-04-20 at 3 21 44 pm](https://user-images.githubusercontent.com/44023728/79716686-d2f6cf00-831a-11ea-852b-5186c79acaaf.png)

**Comment by MrYuion** [comment]
I'd need the data from the backend to display this.
FYI @stakach

**Comment by stakach** [comment]
Commit response already includes the dates
<img width="359" alt="image" src="https://user-images.githubusercontent.com/368013/79717754-d50e5d00-831d-11ea-8ebb-2e4c1ab21604.png">

So maybe just parse that and show a time `from_now - hash_id`
i.e. `3 days ago - 3eeb415`

**Comment by MrYuion** [comment]
@stakach, if it's more than a month should I show the date instead?
