### ISSUE TITLE
Execute command where all params are optional

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#4]
Clicking send on a function where all parameters are optional stops the component from updating (can't select a different function) and does not execute the command.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/368013/77040797-c544e580-6a0c-11ea-8d41-8277a4326767.png">

**Comment by stakach** [comment]
Seems the latest build has introduced a new issue in this regard
![image](https://user-images.githubusercontent.com/368013/77211530-612f3800-6b58-11ea-9a2d-f3a9b4a43b11.png)

Also listing modules on the system page
![image](https://user-images.githubusercontent.com/368013/77211563-786e2580-6b58-11ea-9155-75417be74f2d.png)

**Comment by MrYuion** [comment]
@stakach, I've been a bit confused as to how the module name should be determine.
Can you please clarify that?

**Comment by stakach** [comment]
Module Name should be: `module.driver.name`
Class should be: `module.custom_name || module.name` however `custom_name` should be ignored if `null` or `""` blank.

Then the index on the class column there is just `Class_count_of_class_type`

so Classes above should be
- `PrivateHelper_1`
- `Lighting_1`
- `PrivateHelper_2`

**Comment by MrYuion** [comment]
`module.driver` isn't returned on the index requests.

**Comment by stakach** [comment]
looking good!
