### ISSUE TITLE
Domains -> Application List Empty But Count Valid

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#41]
**Describe the bug**
Viewing the application list it is empty but the header shows it does have items counted.

**To Reproduce**
1. go to domains
2. select a domain
3. click applications

**Expected behavior**
List of applications should be shown to match the count.

**Screenshots**
![Screen Shot 2020-04-20 at 4 45 57 pm](https://user-images.githubusercontent.com/44023728/79721952-9204b780-8326-11ea-8721-8f93cbfaf091.png)

**Comment by MrYuion** [comment]
@stakach, is this still an issue on the backend?

**Comment by MrYuion** [comment]
@stakach, looks to be backend. The request with `owner` query param seems to return values, but with `authority` it always returns nothing.

**Comment by KimBurgess** [comment]
Adding for tracking. Resolved via https://github.com/PlaceOS/rest-api/commit/bb70503a2927d0c05e923d70a86d220d24cddc98.

**Comment by stakach** [comment]
@MrYuion the filter should be working for `authority` however none of the applications are being saved with an `owner_id`

When adding a new app the `owner_id` should be set to the selected domains `id`

**Comment by KimBurgess** [comment]
@stakach should that then also be the same for https://github.com/PlaceOS/init/blob/6eb47aae60c9b9de4d0329b2a2e385b4d0a2ce48/src/tasks/entities.cr#L78-L130?
