### ISSUE TITLE
Admin -> License Management

### ISSUE THREAD

**Issue by jeremy-west** [PlaceOS/backoffice#43]
**Describe the solution you'd like**
Under the admin section, it would be great if we had a license management tab where we can see how many system licenses are consumed and set the number of licenses purchased via the client. 

Using an internal account we can increase or decrease the amount of purchased licenses, in turn preventing the client from adding more licenses without limit than what they have purchased.

**Describe alternatives you've considered**
Nil

**Additional context**
Prevent additional license usage beyond what has been purchased.

**Comment by MrYuion** [comment]
Currently this can be set in the settings.js on the server.
The setting value is represented on the item list sidebar.
<img width="279" alt="Screen Shot 2020-04-22 at 3 07 32 pm" src="https://user-images.githubusercontent.com/20103948/79942932-1a13ca00-84ab-11ea-8aa1-2533996f789e.png">

**Comment by MrYuion** [comment]
Might be something we can add as a property on the authority.

**Comment by caspiano** [comment]
Removing myself as an assignee, I believe there's a solution already in progress for this.

**Comment by caspiano** [comment]
@jeremy24 is this still needed given the advent of Portal?
