### ISSUE TITLE
Users -> Deleting User Error

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#44]
**Describe the bug**
Unable to delete users due to error.

**To Reproduce**
1. Go to: http://pwcme.dev.place.tech/backoffice/#/users/user-En-GsyA5DTr/about
2. Try to delete the no name user

**Expected behavior**
User should be deleted.

**Screenshots**
![Screen Shot 2020-04-22 at 4 07 30 pm](https://user-images.githubusercontent.com/44023728/79946506-7f6bb900-84b3-11ea-9d70-742f26dfd1c5.png)

**Comment by MrYuion** [comment]
@stakach, I'm getting a 404 when trying to delete a user.

**Comment by stakach** [comment]
Yeah lol, it's in a newer build. I'll push a new beta
