### ISSUE TITLE
Users -> Add Existing User Error

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#45]
**Describe the bug**
When adding a new user that duplicates an existing users email address it generates an error and fails to save - can the error message be descriptive to point the user to the actual failure? Current Ajax error does not assist in triaging the issue.

**To Reproduce**
1. Go to users.
2. Add new user.
3. Create new user with same email address as an existing user.

**Expected behavior**
Error should state user could not be saved as email already exists.

**Screenshots**
![Screen Shot 2020-04-22 at 4 11 48 pm](https://user-images.githubusercontent.com/44023728/79946877-30725380-84b4-11ea-9977-5763e9bb29b0.png)

**Comment by MrYuion** [comment]
I'm guessing this is due to not being able to delete the old user.

**Comment by MrYuion** [comment]
@jwest-aca, is this still an issue?

**Comment by jwest-aca** [comment]
@MrYuion yes still the same issue.

**Comment by MrYuion** [comment]
The issue should be fixed in the latest.

**Comment by jwest-aca** [comment]
pulled latest, bug still exists.

**Comment by MrYuion** [comment]
Still looks to be running the same build as before.
<img width="410" alt="Screen Shot 2020-04-28 at 10 37 40 am" src="https://user-images.githubusercontent.com/20103948/80434142-50829680-893c-11ea-8eeb-ab091359e907.png">
