### ISSUE TITLE
Zones -> Parent Dropdown Not Working

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#46]
**Describe the bug**
When adding a new zone, entering text in the parent zone should produce a dropdown with a list of available zones to select as parent.

**To Reproduce**
1.Add new zone.
2. Start typing in parent zone field.
3. no drop down.

**Expected behavior**
drop down should be available to select zones filtered by text entered.

**Screenshots**
![Screen Shot 2020-04-24 at 11 53 09 am](https://user-images.githubusercontent.com/44023728/80167142-f96e8000-8622-11ea-8f30-57350217f27f.png)

**Comment by MrYuion** [comment]
Hmm... not sure this is a bug. The typeahead only shows if there are results. It's directly querying the backend. If nothing shows that means that the backend hasn't returned a result.

**Comment by jwest-aca** [comment]
Correct this is working, appears to have been caused by the elastic crash.
