### ISSUE TITLE
Merged settings do not show until after edit

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/backoffice#47]
**Describe the bug**
When viewing a system, settings inherited from zones do not display in the "Merged" tab until after an edit has been made to the system level settings.

**To Reproduce**
1. Apply setting to a zone
2. Navigate to a system within this zone
3. Look at "Merged" tab - zone level settings do not show
4. Edit system level settings
5. Move backed to "Merged" tab - both zone and system level settings now show.

**Expected behavior**
"Merged" tab should show full merged settings when viewed.

**Comment by MrYuion** [comment]
@caspiano, when creating/updating settings the response will have the `settings_string` encrypted event though the user has the correct access level.
