### ISSUE TITLE
Integrate Kibana

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#48]
Integrate Kibana into a Backoffice tab with a graceful fallback if Kibana is unavailable.

Supported by place-labs/partner-environment#3

**Comment by MrYuion** [comment]
The frontend is already setup for this. I just need a URL to plug in.

**Comment by MrYuion** [comment]
@caspiano, the URL passed to the iFrame with be on the same origin right?
It might be a bit hard to check the status of the iframe contents if it is not.

**Comment by caspiano** [comment]
it will be unless we use a SaaS kibana stack
