### ISSUE TITLE
Domains -> Applications not Shown

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#49]
**Describe the bug**
Applications shows a count of 4, I know there are applications there but they are not shown.

**To Reproduce**
1. Go To Domains -> Applications
2. No Applications are shown despite the count.

**Expected behavior**
Applications are shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/44023728/80778496-eff99080-8bab-11ea-94d8-d789bd8f59b6.png)

**Comment by MrYuion** [comment]
There is already an issue for this #41
