### ISSUE TITLE
Can’t add new application

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/backoffice#5]
Attempting to register a new application from within the domain tab results in a 404.

**Comment by stakach** [comment]
Currently it's posting to `/api/engine/v2/applications/`
Needs to post to `/api/engine/v2/oauth_apps/`

**Comment by MrYuion** [comment]
@stakach, what are the query params for that endpoint? I'm getting 500s on GET requests.

**Comment by stakach** [comment]
OK so you can now filter the list of oauth_apps:

`/api/engine/v2/oauth_apps/?authority=sgrp-1234`

**Comment by MrYuion** [comment]
Is the authority the domain's id?

**Comment by stakach** [comment]
Yeah domains id

**Comment by MrYuion** [comment]
I've updated the request.

**Comment by KimBurgess** [comment]
@MrYuion just tested this - I can see the past happening to `/api/engine/v2/oauth_apps`, which returns a 201 along with the app info.

Once an application has been created though, this is not visible on that view.

**Comment by MrYuion** [comment]
Is it there on a refresh?

**Comment by KimBurgess** [comment]
Nope. Although I do see two requests happening:
1. `/api/engine/v2/oauth_apps?offset=0&limit=1&owner=8uANyvTgKjKPnV` which does look to be returning the created app
2. `/api/engine/v2/oauth_apps?authority=8uANyvTgKjKPnV&offset=0` which is just getting an empty array.
Might need to insight from @stakach on what should be happening here.
