### ISSUE TITLE
Support Interface Repositories

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#50]
- you SHOULD NOT be able to change the commit on a Driver repository
- you SHOULD be able to change the commit on an Interface repository
- commits for interfaces are for the purpose of rolling back, so do not fetch the commits when creating an Interface repository
- you SHOULD use the commits endpoint when someone wants to update an Interface repository

relevant PR: PlaceOS/rest-api#21

**Comment by MrYuion** [comment]
I'm not too sure where I'd use `GET /repositories/interfaces`.

**Comment by MrYuion** [comment]
Getting this error from the `commits` endpoint:
```
ERROR: request to http://127.0.0.1:3000/api/frontends/v1/repositories//www-backoffice/commits?count=50 failed with 404 Not Found
 (PlaceOS::Frontends::ClientError)
  from usr/share/crystal/src/gc/boehm.cr:110:5 in 'get'
  from app/lib/frontends/src/frontends/client.cr:51:18 in 'get__api_engine_v2_repositories___id_commits'
  from app/lib/action-controller/src/action-controller/router/route_handler.cr:255:3 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from usr/share/crystal/src/http/server/request_processor.cr:48:11 in 'process'
  from usr/share/crystal/src/fiber.cr:255:3 in 'run'
  from ???
```

**Comment by caspiano** [comment]
> I'm not too sure where I'd use `GET /repositories/interfaces`.

This may be best revealed in a tab on the admin panel? it shows the current interfaces deployed and what commit they're at.

> Getting this error from the `commits` endpoint:

This is because your cluster is not yet integrated with the `frontends` service.

**Comment by stakach** [comment]
@MrYuion this request should work on the pwcme.dev.place.tech server
