### ISSUE TITLE
Domains -> new applications require refresh to show

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/backoffice#52]
**Describe the bug**
When adding a new application requests are made to:
1. `GET /auth/authority`
2. `POST /api/engine/v2/oauth_apps`

However the application list is no re-queried, or updated with the response from the post call following creation.

**To Reproduce**
1. Go to 'Domains'
2. Click on the domain to test with
3. Click on add new, fill out app details and save.

**Expected behavior**
Application count should update to n+1.

Note: app list does not show at all on current beta branch due to #41, however expected behaviour is application count should update (which is does following a reload).

**Comment by stakach** [comment]
Latest version of the Rest-API is confirmed to be filtering these too

**Comment by kimburgess** [comment]
This behaviour is still occurring in current alpha builds.

**Comment by kimburgess** [comment]
This also applies to UI controls when adding staff API tenants.

**Comment by MrYuion** [comment]
@kimburgess, should be fixed now.
