### ISSUE TITLE
Module automation

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#53]
**Is your feature request related to a problem? Please describe.**

Adding multiple modules to a System is a repetitive task.

**Describe the solution you'd like**

- CSV imports
- add **N** instances of a Module from a single configuration
- Template Systems/Modules (i.e. a set of prefilled forms)

Keen to hear opinions on these :)

**Comment by MrYuion** [comment]
That should be fairly easy to do.
Would it be good to have a request for batching those add requests?
For the N instance thing, would that be creating N new instances from the details of a selected Module?
Templates would be good. Currently I think the driver is being used as a template for a module.
Would we want custom templates or to use other Systems/Modules as templates?

**Comment by caspiano** [comment]
> Would it be good to have a request for batching those add requests?

I think it might be better at this stage to do individual requests

> For the N instance thing, would that be creating N new instances from the details of a selected Module?

Yeah that makes the most sense to me. An action like `Create Modules from...`

> Would we want custom templates or to use other Systems/Modules as templates?

It would probably be easier to support using a System/Module as a template directly. We could potentially keep a repo of solutions we're comfortable sharing in a bulk creation format. yaml/csv.

Or even support something like `Export configuration as...`
