### ISSUE TITLE
Systems -> module reload/recompile does not execute

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/backoffice#59]
**Describe the bug**
When viewing modules in a system, attempting to reload/recompile does not perform any requests when pressing 'OK' on confirmation dialog.

![image](https://user-images.githubusercontent.com/843652/82511616-1f6b3f80-9b51-11ea-8bb3-47826f93427d.png)

**To Reproduce**
1. Go to 'Systems' and select a system
2. View the module tab
3. Select 'Reload module' from within the 3 dot menu next to a module
4. Click 'OK'

**Expected behavior**
Request should be made to reload / recompile (as per endpoint in #54).

**Comment by MrYuion** [comment]
This should already be fixed in the latest alpha build.
