### ISSUE TITLE
Debug console only works intermitantly

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/backoffice#60]
**Describe the bug**
When monitoring a module and using the debug console, functionality of this is intermittent.

It's possible to see log output on the backend, but this is not rendering within the Backoffice "Debug Console" view.

Note: issue may not be front end related (required further investigation), but creating this here for tracking / linking as it is where the symptom is visible.

**To Reproduce**
1. Choose a system
2. Go to modules
3. Start monitoring a module instance
4. Watch debug console and backend logs simultaneously.

**Expected behavior**
Module debug output should always reflect in both locations.

**Comment by stakach** [comment]
@benhoad solving this and the websocket Auth issue would be awesome.

**Comment by MrYuion** [comment]
@KimBurgess, is there a module I can use in the partner-env to test this?

**Comment by KimBurgess** [comment]
If you use the “Logic Example” driver it will generate a [message on settings update](https://github.com/PlaceOS/drivers/blob/master/drivers/place/logic_example.cr#L10).

This may be a downstream issue from PlaceOS/core#40 too.

**Comment by MrYuion** [comment]
@KimBurgess, looks to be working as expected on the frontend.

**Comment by KimBurgess** [comment]
No probs. Cheers for double checking.

With the knowledge that driver debug state does not persist driver stop/start, I’m almost certain that what originally caused this.
