### ISSUE TITLE
Incorrect state shown when module is disconnected

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/backoffice#61]
**Describe the bug**
When a module transitions from connected -> disconnected, state shown in Backoffice does not reflect this. Both the `module[:connected]` status and `connected` attribute in the model returned from rest endpoints indicate as `false`.

**To Reproduce**
1. Go to Systems
2. Click on a system of interest then -> Modules
3. View state

**Expected behavior**
State indicator should show as red if module is not connected.

**Comment by KimBurgess** [comment]
Note: the appears to impact the modules listing under the Systems view only. Viewing the module itself shows it tagged with a 'Offline' pill under the direct Modules view.

**Comment by alexchuvand** [comment]
The `module[:connected]` does not return any value. So the `connected` attribute is always false.

Note: 
the point is red if `connected` is `false` and running is `true`
the point is green if `connected` is `true` and running is `true`

**Comment by alexchuvand** [comment]
As discussed with @stakach , `connected` is not used.

**Comment by stakach** [comment]
the point is red if connected is false and running is true
the point is green if connected is true and running is true

Also
the point is black if running is false
the point is grey if running is true and we don't have a connected value (from the binding)
