### ISSUE TITLE
Warn entries in debug log prefix with `undefined`

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/backoffice#63]
**Describe the bug**
When monitoring driver logs, warning level entries are prefixed with `undefined`.

![image](https://user-images.githubusercontent.com/843652/83613233-dc847f80-a5c6-11ea-8e20-88dca7f6efd4.png)

Websocket message was:
```
{"id":6,"type":"debug","msg":"Timer fired 34","meta":{"sys":"sys-F3Na0hE0A-m","mod":"mod-F3Neb-iV2G-","index":1,"name":"debug"},"mod":"mod-F3Neb-iV2G-","level":"warning"}
```

**Comment by MrYuion** [comment]
This has already been fixed by #56
