### ISSUE TITLE
Adding a new domain

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#65]
**Describe the bug**

When adding a new domain it doesn't seem to send the domain.

![image](https://user-images.githubusercontent.com/368013/84617179-8a6e2300-af11-11ea-9f83-0f2c2b15f425.png)

![image](https://user-images.githubusercontent.com/368013/84617100-4f6bef80-af11-11ea-80e7-94c4c2cbd200.png)

**Comment by stakach** [comment]
Also, trying to edit the domain after saving (to add the missing domain)
Hangs here and then requires you to refresh your browser

<img width="395" alt="image" src="https://user-images.githubusercontent.com/368013/84617367-09fbf200-af12-11ea-81ce-3b2d20420714.png">

**Comment by MrYuion** [comment]
Looks to be send the correct values. Looks like the backend isn't saving the value.

<img width="555" alt="Screen Shot 2020-06-16 at 10 20 54 am" src="https://user-images.githubusercontent.com/20103948/84718072-15efbe80-afbb-11ea-8a93-7055c40d2fdb.png">

**Comment by stakach** [comment]
The field is `domain` not `dom` - which looks to be the issue

**Comment by benhoad** [comment]
found the 'dom' in domains util, will test locally

**Comment by MrYuion** [comment]
Okay. You'll need to change it in the ts client then. Can I get notified when there are API changes like this in the future.

**Comment by benhoad** [comment]
Updated ts-client - what's the publish steps for npm?

**Comment by MrYuion** [comment]
Just commit.
