### ISSUE TITLE
Display more metadata on `About` tabs

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#66]
## All models
- `created_at : time`
- `updated_at : time`

## Module
- `notes : string`
-  `ip : string`
-  `port : number`
-  `tls : boolean`
- `udp : boolean`

## Driver
- `default_uri : string`
- `default_port : number`

**Comment by alexchuvand** [comment]
Added data on all 'About' tabs. There is no 'About' tabs for domain.
