### ISSUE TITLE
Show only device drivers when viewing repository

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#70]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Interfaces and helper functions are also being shown in the list, would be nice to only show device drivers.

**Describe alternatives you've considered**
Maybe driver filenames could be postfixed driver_module_driver.cr?
Or look to see if the file inherits the PlaceOS::Driver class

**Additional context**

**Comment by caspiano** [comment]
This will be rolled out in the next beta, @PhilPearson
Thanks for the issue!
