### ISSUE TITLE
Cannot add logic drivers to a system

### ISSUE THREAD

**Issue by KimBurgess** [PlaceOS/backoffice#72]
**Describe the bug**
When attempting to add a logic driver, the `Save [S]` button appears non responsive. No requests show and nothing logged to the browser console when interacted with.

**To Reproduce**
1. Go to a/any system
2. Navigate to 'Modules'
3. Click on 'Add new'
4. Select a logic driver
5. Attempt to save.

**Expected behavior**
The module should be added to the system, or an error / validation flagged to the user if this is not possible.

**Screenshots**
![image](https://user-images.githubusercontent.com/843652/85352778-143d7200-b54a-11ea-99cb-5e2f3e6c899b.png)

**Comment by alexchuvand** [comment]
Fixed. Even though the `uri` was not required, it was still going through the pattern validator.
