### ISSUE TITLE
Zones -> Display Name Field is Missing

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#74]
**Describe the bug**
Zone Config should have a Display Name Field but it is not there. SVT Confirmed it exists in the api. 

**To Reproduce**
1. Select a Zone
2. Edit Zone
3. Parent and Name are shown but no field for Display Name.

**Comment by alexchuvand** [comment]
Added in this commit 4d809fe754be4135158862eaa932258862b05c39
