### ISSUE TITLE
Bug: Trigger Systems rendering

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#77]
The Systems for a Trigger are not rendering.

![Screen Shot 2020-06-24 at 12 32 17](https://user-images.githubusercontent.com/18466497/85491623-33ee9c00-b617-11ea-85e6-d6828493b019.jpg)

**Comment by alexchuvand** [comment]
Fixed in 2592d642fc0dac9193faca65fe18314e0e887706
