### ISSUE TITLE
Display and edit settings

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#8]
Display and allow editing of settings for Zone, Driver, System and Module at Unencrypted, Support and Admin encryption levels.

There should be a view of the merged results.

**Comment by stakach** [comment]
As discussed on the VC with @w-le these should be editable inline on the about tab when viewing the object.

Future work, not required to close this issue:
* edit module settings directly from the system module tab
* have a diff view where you can see the changes you are making and about to save
