### ISSUE TITLE
Add User -> Modal says 'New Domain'

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#82]
**Describe the bug**
When adding a new user, the add new user modal window states 'New Domain'

**To Reproduce**
1. To to users
2. Click + to add new user
3. Modal title is 'New Domain'

**Expected behavior**
Modal should be 'New User'

**Screenshots**
![image](https://user-images.githubusercontent.com/44023728/85983404-d13c3c80-ba2a-11ea-928f-495428caa88a.png)

**Comment by MrYuion** [comment]
This has already been fix. Just hasn't been merged into master.
