### ISSUE TITLE
New Local Users Unable to Authenticate

### ISSUE THREAD

**Issue by jwest-aca** [PlaceOS/backoffice#83]
**Describe the bug**
After adding new local sys admins via Backoffice, the new users are not able to login to backoffice.

**To Reproduce**
1. Create a new user with username, email and password.
2. Open incognito or whatever and try to login as the user.
3. Will be unable to login.

**Expected behavior**
user should authenticate and login.

**Screenshots**
![image](https://user-images.githubusercontent.com/44023728/85993117-2a12d180-ba39-11ea-9422-f3b6bb1fd08f.png)

**Comment by jwest-aca** [comment]
@stakach FYI - Pretty sure this is a front end bug though.

**Comment by MrYuion** [comment]
That login form isn't part of backoffice. It's a seperate HTML file.
@stakach, can you have a look an make sure it's not sending the wrong data.
