### ISSUE TITLE
adding a driver lists frontend repositories

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#88]
**Describe the bug**

adding a driver lists frontend repositories in the dropdown

Backoffice should not be an option:
![image](https://user-images.githubusercontent.com/368013/86748658-fd396c80-c07f-11ea-96b4-6812c8b773ab.png)

**Comment by caspiano** [comment]
There's currently no support for filtering on repository (backlogged), the filter will eventually be `type=(interface|driver)`

**Comment by MrYuion** [comment]
That's fine. It's easy to add filtering on the frontend.
