### ISSUE TITLE
View error

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#9]
View error on a failed execute request does not show the error response. 

![Screenshot_2020-03-20 Systems PlaceOS](https://user-images.githubusercontent.com/18466497/77128681-13a5c300-6aa5-11ea-85d3-de726425c6a6.png)

![Screenshot_2020-03-20 Systems PlaceOS(1)](https://user-images.githubusercontent.com/18466497/77128680-12749600-6aa5-11ea-9000-2b5fbd656374.png)

**Comment by MrYuion** [comment]
What was it supposed to print out?

**Comment by stakach** [comment]
This might be more for me. It's probably an issue parsing the parameters (i.e. sending a number instead of a string)
Most likely this is not being pumped down the websocket

**Comment by stakach** [comment]
@caspiano @MrYuion this seems to be working now.
Going to close for now, please re-open if you can replicate
