### ISSUE TITLE
New Fields for OAuth authentication

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#97]
I've added two new fields to OAuth authentication that are required to enable features required by a Google client.
https://github.com/PlaceOS/auth/blob/master/app/models/oauth_strat.rb#L19-L23

```
authorize_params = Hash { String: String }
ensure_matching = Hash { String: Array(String) }
```

related to #96 (in that you might as well do these things at the same time)

**Comment by stakach** [comment]
@MrYuion the latest commit has changed the info mappings to a `Hash { String: Array(String) }`
but it should be a `Hash { String: String }`

Looks like `ensure_matching` and `info_mappings` are around the wrong way:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/368013/88763804-17fe8d00-d1b7-11ea-99f0-46279baf012b.png">

also with the `ensure_matching`
How do i enter multiple values - so it sends up an array?

<img width="584" alt="image" src="https://user-images.githubusercontent.com/368013/88763907-56944780-d1b7-11ea-9dbc-d759986ab83d.png">

**Comment by MrYuion** [comment]
Add a comma to separate the values.

**Comment by stakach** [comment]
Sweet, it's working for saving the data.
But when you click edit the fields are empty

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/368013/88773423-6e72c800-d1c5-11ea-84ee-1cb2e1be1855.png">
