### ISSUE TITLE
Unable to use DNS entry for devices

### ISSUE THREAD

**Issue by PhilPearson** [PlaceOS/backoffice#99]
**Describe the bug**
Device drivers do not accept a DNS entry in place of an IP address.

https://github.com/PlaceOS/backoffice/blob/e602841233c370eb98091837913c91a27d561e43/src/app/shared/components/forms/module-form/module-form.component.html#L70

**To Reproduce**
1. Create a  new module (driver must be of type Driver)
2. Enter a dns entry in place of an IP address `lcd-left.mycorp.local`
3. Clicking the Save button does nothing

**Expected behavior**
DNS entries should be allowed in place of an IP address

**Comment by MrYuion** [comment]
@PhilPearson, I don't think the IP address field should take anything other than an IP address. If we're to take a domain name I'd either have to rename the field or create a new field for it.
@stakach, how should I be handling this on the frontend? I don't think giving a domain into an IP address field is appropriate. Maybe the URI field should be used?
